version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql